**TASK 1 **

In [ ]:
# positive, negative, or zero
num = int(input("Enter a number: "))

if num > 0:
    print("The number is positive.")
elif num < 0:
    print("The number is negative.")
else:
    print("The number is zero.")

In [ ]:
# 10 down to 1
print("\nNumbers from 10 down to 1:")
i = 10
while i >= 1:
    print(i)
    i = i - 1

**TASK 2**

In [ ]:
# 5 integers
numbers = [10, 20, 30, 40, 50]

# Print each element
print("The elements in the list are:")
for num in numbers:
    print(num)

In [ ]:
# sum of all elements
total = 0
for num in numbers:
    total = total + num

print("The sum of all elements is:", total)

In [ ]:
# Function to multiply two numbers
def multiply(a, b):
    return a * b

In [ ]:
# Function to square each number in a list
def square_list(numbers):
    squared = []
    for num in numbers:
        squared.append(num * num)
    return squared

In [ ]:
# Demonstrating the functions
result = multiply(5, 3)
print("Multiplication of 5 and 3 is:", result)

In [ ]:
my_list = [1, 2, 3, 4, 5]
print("Original list:", my_list)
print("Squared list:", square_list(my_list))

In [ ]:
# Using random module to generate a random number
import random

random_number = random.randint(1, 100)
print("Random number between 1 and 100:", random_number)

**TASK 3**

In [ ]:
import pandas as pd
import numpy as np

# Load the CSV file into a Pandas DataFrame
file_path = "/content/sample_data.csv"   # replace with your file path if needed
df = pd.read_csv(file_path)

In [ ]:
# Display the DataFrame
print("Full DataFrame:")
print(df, "\n")

Full DataFrame:
   Column1  Column2  Column3
0       10        5        2
1       20       15        4
2       30       25        6
3       40       35        8
4       50       45       10

In [ ]:

# Selecting specific rows (first 3 rows)
selected_rows = df.iloc[0:3]
print("First 3 rows:")
print(selected_rows, "\n")

First 3 rows:
   Column1  Column2  Column3
0       10        5        2
1       20       15        4
2       30       25        6

In [ ]:

# Selecting specific columns (Column1 and Column3)
selected_columns = df[['Column1', 'Column3']]
print("Selected Columns (Column1 & Column3):")
print(selected_columns, "\n")

Selected Columns (Column1 & Column3):
   Column1  Column3
0       10        2
1       20        4
2       30        6
3       40        8
4       50       10

In [ ]:
# NumPy operations on a list/array
array = np.array([10, 20, 30, 40, 50])

mean_val = np.mean(array)
sum_val = np.sum(array)
std_val = np.std(array)

print("NumPy Array Operations:")
print("Array:", array)
print("Mean:", mean_val)
print("Sum:", sum_val)
print("Standard Deviation:", std_val)

NumPy Array Operations:
Array: [10 20 30 40 50]
Mean: 30.0
Sum: 150
Standard Deviation: 14.142135623730951